name: MoonTrek
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pip
  - opencv
  - pip:
    - numpy==1.20.1
    - opencv-contrib-python==3.4.2.17
    # following commented dependencies aren't used by server
    # - django==3.1.7
    # - pillow==8.1.2
    # - pytz==2021.1
    # - sqlparse==0.4.1 
